spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_clientes

spring.datasource.username=postgres
spring.datasource.password=4020

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=clientflow-chave-secreta-super-segura-2026
jwt.expiration= 7200000