spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_clientes

spring.datasource.username=postgres
spring.datasource.password=4020

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=106fff775a25ea1e7a1c2557629171e66540392b6e520f7315d61135405b0c03
jwt.expiration= 7200000